---
- hosts: virthost
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Do not teardown virtual machines by default
      set_fact:
        teardown: false
    - import_tasks: tasks/main.yml
